name: windows-test
on: push
jobs:
  windows-build:
    name: windows-test
    runs-on: windows-2022
    steps:
      - name: Set version
        run: |
          echo "MY_VERSION=$(git describe).substring(1)" >> "$GITHUB_ENV"
      - name: Get version
        run: |
          echo "$MY_VERSION"
